### ISSUE TITLE
Do not 0 out/redirect earned if fees are redirected

### ISSUE THREAD

**Issue by Tritium-VLK** [balancer/protocol_fee_allocator_v2#10]
In protocol allocator V1, if rewards are redirected, the earned is not.  It seems like in V2, the earned is being changed in the redirect logic.  This makes it hard to compare.

Earned should always show how much the pool earned.  The redirect should work by redirect incentives from pools that didn't earn enough to pools that did.  It should be easy to see how much a pool earned and that it didn't earn enough/how much it needed to earn/etc.

**Comment by jalbrekt85** [comment]
> In protocol allocator V1, if rewards are redirected, the earned is not. It seems like in V2, the earned is being changed in the redirect logic. This makes it hard to compare.


the `total_earned_fees_usd` is not being changed in the redirect logic
