### ISSUE TITLE
compare fee run results between allocators

### ISSUE THREAD

**Issue by jalbrekt85** [balancer/protocol_fee_allocator_v2#2]
can load the final csvs and produce a diff

**Comment by jalbrekt85** [comment]
implemented here: https://docs.google.com/spreadsheets/d/1pOxG4NyzZB7k085PDr0J-3kZFqVOPfhXDP_8QxRbpZg/edit?gid=1317668330#gid=1317668330

can copy paste the fee run csv into the `CSV1` and `CSV2` sheets and the `Comparison` sheet will automatically compute the difference

**Comment by jalbrekt85** [comment]
historical run comparison between v1 and v2: https://docs.google.com/spreadsheets/d/1t4DZ5WUxDG6wXCatQJfaHzcb4fBCbvP-v6XCjjuPcwY/edit?gid=1899197203#gid=1899197203

**Comment by Tritium-VLK** [comment]
- Add percentage diff per round, and also symbol per pool
- Think about graphing flows per pool over time comparing the 2 methods. 
- Calculate total % diff of entire set +  per chain (summery stats)
